[rpc]
host = "0.0.0.0"
port = 50051

[firebase]
server_key = ""
url = "https://fcm.googleapis.com/v1/projects/{project_id}/messages:send"

[apns]
team_id = ""
key_id = ""
url = ""
bundle_id = ""

[rabbitmq]
scheme = "amqp"
host = "localhost"
port = 5672
username = "rabbit"
password = "rabbit"

[database]
dsn = "postgres://postgres:postgres@localhost/postgres"